# Generated by Django 4.1 on 2022-08-17 19:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_user_account_number_user_advertiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_watched',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
