# Generated by Django 4.1 on 2022-08-17 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_user_date_watched'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_watched',
            new_name='date_added',
        ),
    ]
