# Generated by Django 3.2 on 2022-08-24 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_watched_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='advertiser',
            new_name='advertisers',
        ),
    ]
